architecture:
  name: "openai/whisper-large-v2"

runtime:
  use_fp16: False
  device: "cuda"

dataloader:
  batch_size: 4
  num_workers: 2
  pin_memory: True

generate:
  num_beams: 5
  do_sample: False
  max_length: 80
  
dataset:
  source_ds: "clotho"
  task: "caption"
