hf_training_args:
  do_train: True
  do_eval: False

  max_steps: 500
  optim: "adamw_torch"
  learning_rate: 0.00001
  warmup_steps: 100

  per_device_train_batch_size: 6
  gradient_accumulation_steps: 7
  per_device_eval_batch_size: 6
  eval_accumulation_steps: 1

  dataloader_num_workers: 16
  dataloader_pin_memory: True
  dataloader_drop_last: False
  dataloader_persistent_workers: True
  dataloader_prefetch_factor: 3

  logging_steps: 1
  report_to: "wandb"
  remove_unused_columns: False # NEVER TOUCH THIS

  fp16: True

  metric_for_best_model: "spider"
  greater_is_better: True

  load_best_model_at_end: True
  predict_with_generate: True # NEVER TOUCH THIS
  generation_num_beams: 1
  generation_max_length: 80
  eval_strategy: "steps"
  eval_steps: 500

  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 5


architecture:
  name: "openai/whisper-small"
  use_pretrained_whisper_encoder: True
  use_pretrained_whisper_decoder: True

early_stopping:
  should_early_stop: False
  early_stopping_patience: null
  early_stopping_threshold: null

logging:
  log_preds_every_n_steps: 50
  # these are per dataset
  log_preds_num_train: 8
  log_preds_num_valid: 32
